# Generated by Django 5.0.6 on 2024-07-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="writer",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="place",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="place",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="place",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="place",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="place",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="place_image", verbose_name="이미지"
            ),
        ),
    ]
