# Generated by Django 5.0.6 on 2024-07-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="writer",
            new_name="userid",
        ),
        migrations.RenameField(
            model_name="community",
            old_name="writer",
            new_name="user",
        ),
    ]
