# Generated by Django 5.0.6 on 2024-07-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_rename_writer_comment_userid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="userid",
            new_name="user",
        ),
    ]
