# Generated by Django 5.0.6 on 2024-07-09 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_rename_userid_comment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="likes",
            field=models.ManyToManyField(
                related_name="like_community", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
